export  const projectsImages = [
    {
        id:1,
        img:"new way.png",
        link:""
    },
    {
        id:2,
        img:"matflix.png",
        link:""
    },
    {
        id:3,
        img:"e-commerce.png",
        link:""
    }
]
export  const langImages = [
    {
        id:1,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/2048px-HTML5_logo_and_wordmark.svg.png",
    },
    {
        id:2,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1200px-CSS3_logo_and_wordmark.svg.png",
        link:""
    },
    {
        id:3,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
        link:""
    },
    {
        id:4,
        img:"https://seeklogo.com/images/M/microsoft-net-logo-4D9DA1DB77-seeklogo.com.png",
        link:""
    },
    {
        id:5,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/1280px-Node.js_logo.svg.png",
        link:""
    },
    {
        id:6,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/1024px-Unofficial_JavaScript_logo_2.svg.png",
        link:""
    },
    {
        id:7,
        img:"https://www.svgrepo.com/show/303232/mongodb-logo.svg",
        link:""
    },
    {
        id:8,
        img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sass_Logo_Color.svg/1280px-Sass_Logo_Color.svg.png",
        link:""
    }
]